/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as BanksRouteImport } from './routes/banks'
import { Route as DnsRouteImport } from './routes/dns'
import { Route as EarthRouteImport } from './routes/earth'
import { Route as InfraRouteImport } from './routes/infra'
import { Route as InternationalRouteImport } from './routes/international'
import { Route as KabuPreviewRouteImport } from './routes/kabu-preview'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MeRouteImport } from './routes/me'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PayRouteImport } from './routes/pay'
import { Route as PayoutRouteImport } from './routes/payout'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReliefRouteImport } from './routes/relief'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as XrpRouteImport } from './routes/xrp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const BanksRoute = BanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsRoute = DnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => rootRouteImport,
} as any)
const EarthRoute = EarthRouteImport.update({
  id: '/earth',
  path: '/earth',
  getParentRoute: () => rootRouteImport,
} as any)
const InfraRoute = InfraRouteImport.update({
  id: '/infra',
  path: '/infra',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalRoute = InternationalRouteImport.update({
  id: '/international',
  path: '/international',
  getParentRoute: () => rootRouteImport,
} as any)
const KabuPreviewRoute = KabuPreviewRouteImport.update({
  id: '/kabu-preview',
  path: '/kabu-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutRoute = PayoutRouteImport.update({
  id: '/payout',
  path: '/payout',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReliefRoute = ReliefRouteImport.update({
  id: '/relief',
  path: '/relief',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const XrpRoute = XrpRouteImport.update({
  id: '/xrp',
  path: '/xrp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/banks': typeof BanksRoute
  '/dns': typeof DnsRoute
  '/earth': typeof EarthRoute
  '/infra': typeof InfraRoute
  '/international': typeof InternationalRoute
  '/kabu-preview': typeof KabuPreviewRoute
  '/ledger': typeof LedgerRoute
  '/library': typeof LibraryRoute
  '/live': typeof LiveRoute
  '/me': typeof MeRoute
  '/monitor': typeof MonitorRoute
  '/news': typeof NewsRoute
  '/pay': typeof PayRoute
  '/payout': typeof PayoutRoute
  '/register': typeof RegisterRoute
  '/relief': typeof ReliefRoute
  '/services': typeof ServicesRoute
  '/xrp': typeof XrpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/banks': typeof BanksRoute
  '/dns': typeof DnsRoute
  '/earth': typeof EarthRoute
  '/infra': typeof InfraRoute
  '/international': typeof InternationalRoute
  '/kabu-preview': typeof KabuPreviewRoute
  '/ledger': typeof LedgerRoute
  '/library': typeof LibraryRoute
  '/live': typeof LiveRoute
  '/me': typeof MeRoute
  '/monitor': typeof MonitorRoute
  '/news': typeof NewsRoute
  '/pay': typeof PayRoute
  '/payout': typeof PayoutRoute
  '/register': typeof RegisterRoute
  '/relief': typeof ReliefRoute
  '/services': typeof ServicesRoute
  '/xrp': typeof XrpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/banks': typeof BanksRoute
  '/dns': typeof DnsRoute
  '/earth': typeof EarthRoute
  '/infra': typeof InfraRoute
  '/international': typeof InternationalRoute
  '/kabu-preview': typeof KabuPreviewRoute
  '/ledger': typeof LedgerRoute
  '/library': typeof LibraryRoute
  '/live': typeof LiveRoute
  '/me': typeof MeRoute
  '/monitor': typeof MonitorRoute
  '/news': typeof NewsRoute
  '/pay': typeof PayRoute
  '/payout': typeof PayoutRoute
  '/register': typeof RegisterRoute
  '/relief': typeof ReliefRoute
  '/services': typeof ServicesRoute
  '/xrp': typeof XrpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/banks'
    | '/dns'
    | '/earth'
    | '/infra'
    | '/international'
    | '/kabu-preview'
    | '/ledger'
    | '/library'
    | '/live'
    | '/me'
    | '/monitor'
    | '/news'
    | '/pay'
    | '/payout'
    | '/register'
    | '/relief'
    | '/services'
    | '/xrp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/banks'
    | '/dns'
    | '/earth'
    | '/infra'
    | '/international'
    | '/kabu-preview'
    | '/ledger'
    | '/library'
    | '/live'
    | '/me'
    | '/monitor'
    | '/news'
    | '/pay'
    | '/payout'
    | '/register'
    | '/relief'
    | '/services'
    | '/xrp'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/banks'
    | '/dns'
    | '/earth'
    | '/infra'
    | '/international'
    | '/kabu-preview'
    | '/ledger'
    | '/library'
    | '/live'
    | '/me'
    | '/monitor'
    | '/news'
    | '/pay'
    | '/payout'
    | '/register'
    | '/relief'
    | '/services'
    | '/xrp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  BanksRoute: typeof BanksRoute
  DnsRoute: typeof DnsRoute
  EarthRoute: typeof EarthRoute
  InfraRoute: typeof InfraRoute
  InternationalRoute: typeof InternationalRoute
  KabuPreviewRoute: typeof KabuPreviewRoute
  LedgerRoute: typeof LedgerRoute
  LibraryRoute: typeof LibraryRoute
  LiveRoute: typeof LiveRoute
  MeRoute: typeof MeRoute
  MonitorRoute: typeof MonitorRoute
  NewsRoute: typeof NewsRoute
  PayRoute: typeof PayRoute
  PayoutRoute: typeof PayoutRoute
  RegisterRoute: typeof RegisterRoute
  ReliefRoute: typeof ReliefRoute
  ServicesRoute: typeof ServicesRoute
  XrpRoute: typeof XrpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banks': {
      id: '/banks'
      path: '/banks'
      fullPath: '/banks'
      preLoaderRoute: typeof BanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns': {
      id: '/dns'
      path: '/dns'
      fullPath: '/dns'
      preLoaderRoute: typeof DnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earth': {
      id: '/earth'
      path: '/earth'
      fullPath: '/earth'
      preLoaderRoute: typeof EarthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra': {
      id: '/infra'
      path: '/infra'
      fullPath: '/infra'
      preLoaderRoute: typeof InfraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international': {
      id: '/international'
      path: '/international'
      fullPath: '/international'
      preLoaderRoute: typeof InternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kabu-preview': {
      id: '/kabu-preview'
      path: '/kabu-preview'
      fullPath: '/kabu-preview'
      preLoaderRoute: typeof KabuPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payout': {
      id: '/payout'
      path: '/payout'
      fullPath: '/payout'
      preLoaderRoute: typeof PayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relief': {
      id: '/relief'
      path: '/relief'
      fullPath: '/relief'
      preLoaderRoute: typeof ReliefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xrp': {
      id: '/xrp'
      path: '/xrp'
      fullPath: '/xrp'
      preLoaderRoute: typeof XrpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  BanksRoute: BanksRoute,
  DnsRoute: DnsRoute,
  EarthRoute: EarthRoute,
  InfraRoute: InfraRoute,
  InternationalRoute: InternationalRoute,
  KabuPreviewRoute: KabuPreviewRoute,
  LedgerRoute: LedgerRoute,
  LibraryRoute: LibraryRoute,
  LiveRoute: LiveRoute,
  MeRoute: MeRoute,
  MonitorRoute: MonitorRoute,
  NewsRoute: NewsRoute,
  PayRoute: PayRoute,
  PayoutRoute: PayoutRoute,
  RegisterRoute: RegisterRoute,
  ReliefRoute: ReliefRoute,
  ServicesRoute: ServicesRoute,
  XrpRoute: XrpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
